services:
  - type: web
    name: points-booth-tracking
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    pullRequestPreviewsEnabled: false
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
